version: '3.1'

services:
  gitoad:
    build: .
    env_file:
      - .env
    ports:
      - "5001:5001"

  postgres:
    image: postgres:15
    environment:
      env_file:
        postgres.env
    ports:
      - "5433:5432"

